-- Packer
require('plugins')
-- Config
require('settings')
require('settings.completion')
require('settings.color')
-- LSP Config
require('lsp')
-- Plugins config
require('plugins.which-key')
require('plugins.galaxyline')
require('plugins.toggleterm')
require('plugins.hlslens')
require('plugins.treesitter')
require('plugins.gitsigns')
require('plugins.nvim-autopairs')
require('plugins.nvim-ts-rainbow')
require('plugins.nvimtree')
require('plugins.indent-blankline')
require('plugins.telescope')
require('plugins.vim-rooter')
require('plugins.vim-signature')
require('plugins.lspkind')
require('plugins.diffview')
require('plugins.todo-comments')
require('plugins.nvim-comment')
require('plugins.lint')
require('plugins.specs')
require('plugins.trouble')
-- Keymap
require('settings.keymap')
